if: branch =~ ^main$|^development|^release

language: node_js
node_js: 12
group: stable
dist: trusty
os: linux

before_install: npm install -g yarn@^1.10.0
install: yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      language: node_js
      script:
        - yarn test

    - stage: publish
        name: 'bump version to beta and publish'
        language: node_js
        script: |
          set -e
          yarn bumpVersion:release
        skip_cleanup: true
        on:
          all_branches: true
        if: (branch =~ /^(release*)/) AND type != pull_request AND !(commit_message =~ /(\[skip release-ci\])/)
