if: branch =~ ^main$|^development|^release

language: node_js
node_js: 12
group: stable
dist: trusty
os: linux

install: yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      language: node_js
      script:
        - yarn test
