if: branch =~ ^main$|^development|^release

language: node_js
node_js: 12
group: stable
dist: trusty
os: linux

deploy:
  provider: pages:git
  token: ${GITHUG_TOKEN}
  edge: true

before_script: |
  git config user.email "snile657@outlook.com"
  git config user.name "crycime"

before_install: npm install -g yarn@^1.10.0
install: yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      language: node_js
      script:
        - yarn test

    - stage: publish
      name: 'bump version to stable production and publish'
      language: node_js
      script: |
        set -e
        yarn bumpVersion:main
        git config user.email "snile657@outlook.com"
        git config user.name "crycime"
        git add .
        git push --verbose --no-verify --follow-tags --quiet "https://${GITHUG_TOKEN}@github.com/crycime/sam_cli.git" HEAD:${TRAVIS_BRANCH}
      skip_cleanup: true
      on:
        all_branches: true
      if: (branch =~ /^(main*)/) AND type != pull_request AND !(commit_message =~ /(\[skip main-ci\])/)
