if: branch =~ ^main$|^development|^release

language: node_js
node_js: 12
group: stable
dist: trusty
os: linux

before_script: |
  git config user.email "snile657@outlook.com"
  git config user.name "crycime"

before_install: npm install -g yarn@^1.10.0
install: yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      language: node_js
      script:
        - yarn test

    - stage: publish
      name: 'bump version to beta and publish'
      language: node_js
      script: |
        set -e
        chmod +x scripts/npm-publish.js
        yarn bumpVersion:release
        git add .
        git push --verbose --no-verify --follow-tags --quiet "https://${GITHUG_TOKEN}@github.com/crycime/sam_cli.git" HEAD:${TRAVIS_BRANCH}
      deploy:
        provider: npm
        email: snile657@outlook.com
        api_key: "$NPM_TOKEN"
        tag: beta
        skip_cleanup: true
        on:
          all_branches: true
      if: (branch =~ /^(release*)/) AND type != pull_request AND !(commit_message =~ /(\[skip release-ci\])/)

    - stage: publish
      name: 'bump version to stable production and publish'
      language: node_js
      script: |
        set -e
        chmod +x scripts/npm-publish.js
        yarn bumpVersion:main
        git add .
        git push --verbose --no-verify --follow-tags --quiet "https://${GITHUG_TOKEN}@github.com/crycime/sam_cli.git" HEAD:${TRAVIS_BRANCH}
      deploy:
        provider: npm
        email: snile657@outlook.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
      if: (branch =~ /^(main*)/) AND type != pull_request AND !(commit_message =~ /(\[skip main-ci\])/)
