name: bump version to stable production and publish

on: [push, pull_request]

jobs:
  publish:
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'main') && !contains(github.event.head_commit.message, 'skip main-ci') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Commit files
        run: |
          git config --global user.email "snile657@outlook.com"
          git config --global user.name "crycime"
          yarn install --frozen-lockfile
          yarn bumpVersion:main
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm publish
          git add .
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
