name: Node.js CI

on: [push, pull_request]

defaults:
  runs-on: ubuntu-latest
  strategy:
      matrix:
        node-version: [14.x]
  run: |
    npm install -g yarn@^1.10.0
    yarn install --frozen-lockfile

jobs:
  unit_test:
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test

  publish_beta:
    steps:
       - if: ${{ contains(github.ref, 'main') && github.event_name == 'push' }}
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
           cache: 'yarn'
       - run: |
           set -e
           chmod +x scripts/npm-publish.js
           yarn bumpVersion:release
           git add .
           git push --verbose --no-verify --follow-tags origin HEAD:${TRAVIS_BRANCH}
