name: Node.js CI

on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: |
          yarn install --frozen-lockfile
          yarn test

  publish_beta:
    if: ${{ contains(github.ref, 'main') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: bump version to beta and publish
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: |
          set -e
          chmod +x scripts/npm-publish.js
          yarn install --frozen-lockfile
          yarn bumpVersion:release
          git config --global user.email "snile657@outlook.com"
          git config --global user.name "crycime"
          git add .
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
